[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tkernel/linker.ld",
    "-C", "link-arg=-static",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-z",
    "-C", "link-arg=max-page-size=0x1000",
    "-C", "relocation-model=static",
]

[alias]
xtask = "run -p xtask --"
