[package]
name = "vanta-userland"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
vanta-abi = { path = "../abi" }
vanta-services = { path = "../services" }

[[bin]]
name = "init"
path = "src/bin/init.rs"

[[bin]]
name = "vsh"
path = "src/bin/vsh.rs"

[[bin]]
name = "echo"
path = "src/bin/echo.rs"

[[bin]]
name = "cat"
path = "src/bin/cat.rs"

[[bin]]
name = "true"
path = "src/bin/true.rs"

[[bin]]
name = "false"
path = "src/bin/false.rs"

[[bin]]
name = "native-gate"
path = "src/bin/native_gate.rs"

[[bin]]
name = "procd"
path = "src/bin/procd.rs"

[[bin]]
name = "service-test"
path = "src/bin/service_test.rs"


[[bin]]
name = "vfsd"
path = "src/bin/vfsd.rs"

[[bin]]
name = "auditd"
path = "src/bin/auditd.rs"

[[bin]]
name = "displayd"
path = "src/bin/displayd.rs"

[[bin]]
name = "desktop"
path = "src/bin/desktop.rs"

[[bin]]
name = "audiod"
path = "src/bin/audiod.rs"
